sequenceDiagram
    participant User
    participant NewFiles
    participant Orchestrator
    participant Transcoder
    participant Cataloguer
    participant MediaLibrary
    participant NotificationSystem
    User->>NewFiles: 0. Add files
    NewFiles->>Orchestrator: 1. Register New Job
    Orchestrator->>Transcoder: 2. Send job for transcoding
    Transcoder-->>Orchestrator: 3. Transcode Complete
    Orchestrator->>Cataloguer: 4. Send Job for Cataloguing
    Cataloguer->>MediaLibrary: 5. Sends file to Media Library
    Cataloguer-->>Orchestrator: 6. Catalogue Complete
    Orchestrator->>NotificationSystem: 7. Notify User
    NotificationSystem-->>User: Media ready
